### ISSUE TITLE
Coverage file format

### ISSUE THREAD

**Issue by Mr-Pepe** [andreaskapou/Melissa#2]
The vignette states that the Bismark coverage file has the following format:
Line 59: <chr> <start> <end> <met_prcg> <met_reads> <unmet_reads>

But the .process_bismark_file function expects a 5 column input:
Line 80: colnames(data) <- c("chr","pos", "met_prcg", "met_reads","unnmet_reads")

**Comment by andreaskapou** [comment]
Hi,

Thanks again for pointing this out. I updated the function to accept a `format` parameter, where the user can choose which format the **coverage** file has. Default is the one with 6 columns:
`<chr> <start> <end> <met_prcg> <met_reads> <unmet_reads>`, to match the vignette file.

These changes will not be available on the stable version of Bioconductor, however you can obtain the latest version of Melissa from Github:
`devtools::install_github("andreaskapou/Melissa")`

Best,
Andreas

**Comment by andreaskapou** [comment]
Assuming this is resolved and closing issue.
